###############################################################
# SPDX-FileCopyrightText: (C) Copyright 2023 Regione Piemonte
#
# SPDX-License-Identifier: EUPL-1.2
###############################################################


driver=org.postgresql.Driver
url=@db.url@
user=@db.user@
pass=@db.pass@
maxRetryAttemps=10
incrementalRetryMills=1000


