###############################################################
# SPDX-FileCopyrightText: (C) Copyright 2023 Regione Piemonte
#
# SPDX-License-Identifier: EUPL-1.2
###############################################################


# true per mandare le  mail (test) SEMPRE e SOLO a mail.test.destinatario
mail.test.flag=@mail.test.flag@
mail.test.destinatario=@mail.test.destinatario@
mail.smtp.host=mailfarm.csi.it
mail.smtp.port=25
mail.mittente.indirizzo=@mail.mittente.indirizzo@
mail.mittente.alias=@mail.mittente.alias@
mail.default.destinatario=@mail.default.destinatario@
mail.destinatario.notifica.fallito.invio.rt.fruitore=@mail.destinatario.notifica.fallito.invio.rt.fruitore@
