fpath.dir=FPATHS/SKPAR

mitt.posta=ufficio.schedulazione@csi.it
dest.posta=irene.etzi@csi.it

#endPointUrl=http://tst-pdd.ruparpiemonte.it/openspcoop/PD/PDNodoDeiPagamentiDellaPATest/PagamentiTelematiciRPT6T/
azione=nodoChiediElencoFlussiRendicontazione
azione_singolo_flusso=nodoChiediFlussoRendicontazione
numero_retry=3
#identificativoDominio=80087670016
#identificativoIntermediarioPA=01995120019
#identificativoStazioneIntermediarioPA=01995120019_01
#password=PIEMONT3

javahome=/usr/local/lang/jdk1.8.0_71

keystore.dir=/skedul/keystore/mdp-int-01

