###############################################################
# SPDX-FileCopyrightText: (C) Copyright 2023 Regione Piemonte
#
# SPDX-License-Identifier: EUPL-1.2
###############################################################

#### Database
db.url=jdbc:postgresql://dbs-mdpnew-dev-001p.site02.nivolapiemonte.it:5432/TEST?connectTimeout=30&socketTimeout=60
db.user=mdpnew_rw
db.pass=MrwDp.)01((

#### Mail
mail.test.flag=true
mail.test.destinatario=antonio.colucci@consulenti.csi.it 
mail.default.destinatario=antonio.colucci@consulenti.csi.it 
mail.smtp.host=mailfarm.csi.it
mail.smtp.port=25
mail.mittente.indirizzo=servizio.mdp@csi.it
mail.mittente.alias=SERVIZIO MDP - AMBIENTE DEV
mail.destinatario.notifica.fallito.invio.rt.fruitore=servizio.mdp@csi.it

