###############################################################
# SPDX-FileCopyrightText: (C) Copyright 2023 Regione Piemonte
#
# SPDX-License-Identifier: EUPL-1.2
###############################################################


@log.level@=INFO
@log.file@=/skedul/java/mdpnew-int-01/mdpetl/log/mdpetl.log

lineaCliente=int-01

#### Database
@db.driver@=org.postgresql.Driver
@db.url@=jdbc:postgresql://pgsql3.csi.it:5433/PGPRD03
@db.user@=mdpnew_rw
@db.pass@=MDP20_x2

#### Mail
@mail.test.flag@=false
@mail.test.destinatario@=irene.etzi@csi.it
@mail.default.destinatario@=irene.etzi@csi.it
@mail.smtp.host@=mailfarm-app.csi.it
@mail.smtp.port@=25
@mail.mittente.indirizzo@=servizio.mdp@csi.it
@mail.mittente.alias@=SERVIZIO MDP
@mail.destinatario.notifica.fallito.invio.rt.fruitore@=servizio.mdp@csi.it

