###############################################################
# SPDX-FileCopyrightText: (C) Copyright 2023 Regione Piemonte
#
# SPDX-License-Identifier: EUPL-1.2
###############################################################



#### Database
# @db.url@=jdbc:postgresql://tst-domdb35.csi.it:5432/PGTST01
db.url=jdbc:postgresql://10.138.167.218:5432/TEST?connectTimeout=30&socketTimeout=60
db.user=mdpnew_rw
db.pass=MyPass8!

#### Mail
mail.test.flag=false
mail.test.destinatario=antonio.colucci@consulenti.csi.it 
mail.default.destinatario=antonio.colucci@consulenti.csi.it 
mail.smtp.host=mailfarm.csi.it
mail.smtp.port=25
mail.mittente.indirizzo=servizio.mdp@csi.it
mail.mittente.alias=SERVIZIO MDP - AMBIENTE TEST
mail.destinatario.notifica.fallito.invio.rt.fruitore=servizio.mdp@csi.it



