###############################################################
# SPDX-FileCopyrightText: (C) Copyright 2023 Regione Piemonte
#
# SPDX-License-Identifier: EUPL-1.2
###############################################################


driver=org.postgresql.Driver
url=jdbc:postgresql://10.138.167.218:5432/TEST?connectTimeout=30&socketTimeout=60
user=mdpnew_rw
pass=MyPass8!
maxRetryAttemps=10
incrementalRetryMills=1000


