###############################################################
# SPDX-FileCopyrightText: (C) Copyright 2023 Regione Piemonte
#
# SPDX-License-Identifier: EUPL-1.2
###############################################################


# true per mandare le  mail (test) SEMPRE e SOLO a mail.test.destinatario
mail.test.flag=false
mail.test.destinatario=antonio.colucci@consulenti.csi.it 
mail.smtp.host=mailfarm.csi.it
mail.smtp.port=25
mail.mittente.indirizzo=servizio.mdp@csi.it
mail.mittente.alias=SERVIZIO MDP - AMBIENTE TEST
mail.default.destinatario=antonio.colucci@consulenti.csi.it 
mail.destinatario.notifica.fallito.invio.rt.fruitore=servizio.mdp@csi.it
